version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - foyer-network



  app:
    image: fouratch/reservation-app:latest
    build: .
    ports:
      - "8089:8089"
    depends_on:
      - db
    networks:
      - foyer-network

networks:
  foyer-network:

volumes:
  db-data: